# Generated by Django 5.2 on 2025-10-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voiceprint_file',
            field=models.FileField(blank=True, null=True, upload_to='voiceprints/'),
        ),
    ]
