# Generated by Django 5.2 on 2025-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_voiceprint_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voiceprint_sample_1',
            field=models.FileField(blank=True, null=True, upload_to='voiceprints/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voiceprint_sample_2',
            field=models.FileField(blank=True, null=True, upload_to='voiceprints/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voiceprint_sample_3',
            field=models.FileField(blank=True, null=True, upload_to='voiceprints/'),
        ),
    ]
