# Generated by Django 5.2 on 2025-11-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_voiceprint_sample_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voiceprint_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
