# Generated by Django 5.2 on 2025-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_voiceprint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eagle_speaker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
