# Generated by Django 5.2 on 2025-11-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_eagle_speaker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='voiceprint_id',
        ),
    ]
